import type { Brand } from "./types";

export const black_and_decker: Brand = {
    slug: "black-and-decker",
    name: "Black+Decker",
    logoSrc: "/logos/black-and-decker-logo.svg",
    description: "Black+Decker pru\u017ea izvanrednu kolekciju alata koja zadovoljava \u0161irok spektar potreba profesionalaca i entuzijasta \u0161irom sveta.",
    heroDescription: { sr: "Black+Decker alati - Uvoznik za Srbiju", en: "Black+Decker Tools - Importer for Serbia" },
    paragraphs: [
      {
        title: { sr: "Istorijat", en: "History" },
        body: {
          sr: "Black & Decker, poznat svetski proizvo\u0111a\u010d elektri\u010dnih alata i opreme za doma\u0107instvo, osnovan je 1910. godine od strane S. Duncana Blacka i Alonza G. Deckera. Kompanija je zapo\u010dela kao mala ma\u0161inska radionica u Baltimoru, ali se brzo istakla na tr\u017ei\u0161tu zahvaljuju\u0107i inovacijama. Ve\u0107 1917. godine patentirana je prva ru\u010dna elektri\u010dna bu\u0161ilica sa okida\u010dem, alat koji je postavio temelj za modernu proizvodnju elektri\u010dnih alata. Te iste godine otvorena je i prva fabrika u Towsonu, Maryland.\n\nTokom narednih decenija, Black & Decker konstantno \u0161iri svoje poslovanje. Kupovinom Van Dorn Electric Tool Company 1928. godine i izlaskom na Njujor\u0161ku berzu 1936. godine, kompanija u\u010dvr\u0161\u0107uje svoju poziciju lidera u industriji alata. Nakon Drugog svetskog rata, nagra\u0111ena je Army-Navy E nagradom za izuzetnu proizvodnju. Do 1960. godine, Black & Decker preuzima DeWalt, \u010dime dodatno \u0161iri svoj portfolio elektri\u010dnih i industrijskih alata.\n\nU periodu od 1975. godine, Black & Decker je nastavio sa akvizicijama, uklju\u010duju\u0107i General Electric (1984) i Emhart Corporation (1989), \u010dime je oja\u010dao ponudu malih aparata i ru\u010dnih alata. Kompanija je uvr\u0161tena u Space Foundation\u2019s Space Technology Hall of Fame zahvaljuju\u0107i razvoju be\u017ei\u010dnih alata koji su kori\u0161\u0107eni u svemirskim misijama. Godine 2010. dolazi do spajanja sa Stanley Works, \u010dime nastaje Stanley Black & Decker, globalni gigant u oblasti proizvodnje alata.\n\nNakon tog spajanja, kompanija se i dalje razvija. Godine 2012. prodaje sektor za hardver i pobolj\u0161anje doma\u0107instava, a 2014. se rebrendira u Black+Decker. Kupovina brenda Craftsman od Sears-a 2017. dodatno pro\u0161iruje asortiman. Iste godine, sklapa se i licencni ugovor sa Stovekraft-om za distribuciju proizvoda u Indiji. Do 2025. godine, Indkal Technologies zapo\u010dinje proizvodnju Black+Decker pametnih televizora za indijsko tr\u017ei\u0161te.",
          en: "Black & Decker, a globally recognized manufacturer of power tools and home equipment, was founded in 1910 by S. Duncan Black and Alonzo G. Decker. The company started as a small machine shop in Baltimore but quickly gained attention due to its innovation. In 1917, they patented the first portable electric drill with a trigger switch, a revolutionary power tool that laid the foundation for the modern tool industry. That same year, the first manufacturing plant opened in Towson, Maryland.\n\nOver the following decades, Black & Decker continued to grow. The acquisition of Van Dorn Electric Tool Company in 1928 and listing on the New York Stock Exchange in 1936 solidified its leadership in the power tool market. After WWII, the company received the Army-Navy E Award for excellence in manufacturing. By 1960, it had acquired DeWalt, further expanding its electric and industrial tool portfolio.\n\nFrom 1975, Black & Decker pursued major acquisitions, including the small appliance division from General Electric in 1984 and Emhart Corporation in 1989. Their innovation in cordless tools earned them a place in the Space Foundation\u2019s Space Technology Hall of Fame. In 2010, the merger with Stanley Works created Stanley Black & Decker, a global powerhouse in tool manufacturing.\n\nPost-merger, the company continued to evolve. In 2012, it sold its hardware and home improvement division, and in 2014, rebranded to Black+Decker. The acquisition of the Craftsman brand in 2017 and a licensing deal with Stovekraft for Indian distribution further expanded the brand. By 2025, Indkal Technologies began manufacturing Black+Decker smart TVs for the Indian market.",
        },
      },
      {
        title: { sr: "Tehnologije i inovacije", en: "Technologies and innovations" },
        body: {
          sr: "Black+Decker alati poznati su po tehnolo\u0161kim inovacijama koje su promenile industriju elektri\u010dnih alata. Jo\u0161 1917. godine razvijen je prvi ru\u010dni elektri\u010dni \u010deki\u0107 sa pi\u0161toljskom dr\u0161kom, alat koji je postao industrijski standard. Godine 1961. uvode se be\u017ei\u010dni alati koji koriste litijum-jonske baterije, \u010dime je Black+Decker postao pionir u oblasti akumulatorskih alata.\n\nKasnije inovacije uklju\u010duju naprednu Li-ion tehnologiju za du\u017ee trajanje baterija, kao i AutoSense, pametnu tehnologiju koja automatski pode\u0161ava snagu odvija\u010da. Kompanija je tako\u0111e razvila sofisticirane sisteme za \u010di\u0161\u0107enje doma, kao i efikasne ure\u0111aje za ba\u0161tenske radove.",
          en: "Black+Decker tools are renowned for innovations that transformed the power tool industry. In 1917, they developed the first pistol-grip electric drill. By 1961, they introduced cordless tools powered by lithium-ion batteries, making them a pioneer in battery-powered tool technology.\n\nRecent innovations include advanced Li-ion battery technology for longer runtime and AutoSense technology that intelligently adjusts torque. The company has also improved home cleaning devices and offers efficient garden maintenance solutions.",
        },
      },
      {
        title: { sr: "Asortiman proizvoda", en: "Product range" },
        body: {
          sr: "Black+Decker nudi izuzetno \u0161irok asortiman proizvoda, uklju\u010duju\u0107i elektri\u010dne alate, akumulatorske alate, opremu za ba\u0161tu i ure\u0111aje za \u010di\u0161\u0107enje. Njihovi alati su dizajnirani za profesionalce, hobiste, ali i za svakodnevnu upotrebu u doma\u0107instvu.\n\nElektri\u010dni alati kao \u0161to su bu\u0161ilice, testerice, brusilice i odvija\u010di poznati su po pouzdanosti i ergonomiji. Akumulatorski alati, koji koriste naprednu litijum-jonsku tehnologiju, pru\u017eaju visoke performanse bez potrebe za kablovima. Alati su laki za upotrebu i brzo se pune, \u0161to ih \u010dini idealnim za rad na terenu i kod ku\u0107e.\n\nU segmentu alata za ba\u0161tu, Black+Decker nudi kosilice, trimere, duva\u010de li\u0161\u0107a i testere za grane, sve dizajnirano da olak\u0161a odr\u017eavanje dvori\u0161ta. Pored toga, kompanija nudi i ku\u0107ne ure\u0111aje za \u010di\u0161\u0107enje poput usisiva\u010da i paro\u010dista\u010da, koji garantuju visok nivo higijene u domu.\n\nBlack+Decker alati kombinuju funkcionalnost, izdr\u017eljivost i modernu tehnologiju, \u010dime zadovoljavaju \u0161irok spektar potreba potro\u0161a\u010da \u0161irom sveta.",
          en: "Black+Decker offers a vast range of products, including power tools, cordless tools, garden equipment, and cleaning devices, all designed to meet the diverse needs of professionals and everyday users.\n\nTheir power tools, such as drills, saws, grinders, and screwdrivers, are known for reliability and ergonomic design. Cordless tools, powered by lithium-ion technology, provide cable-free freedom, fast charging, and powerful performance for both home and job site tasks.\n\nIn the gardening segment, Black+Decker provides lawn mowers, trimmers, leaf blowers, and branch cutters, tools designed to simplify yard maintenance. Their home cleaning devices, including vacuums and steam cleaners, ensure hygienic and spotless environments.\n\nBlack+Decker tools blend functionality, durability, and modern technology to meet the evolving demands of users around the world.",
        },
      },
    ],
    catalogs: [
    ],
    color: "#FFA43B",
    storeUrl: "https://www.prodavnicaalata.rs/proizvodjaci/black-and-decker/",
  };
