import type { Brand } from "./types";

export const dewalt: Brand = {
    slug: "dewalt",
    name: "DeWalt",
    logoSrc: "/logos/dewalt-logo.svg",
    description: "DeWalt alati su jedni od najkvalitetnijih alata dana\u0161njice. Koriste se u svim industrijama i nema prete\u0161kog posla za DeWalt profesionalne ma\u0161ine.",
    heroDescription: { sr: "DeWALT alati - Uvoznik za Srbiju", en: "DeWalt Tools - Importer for Serbia" },
    paragraphs: [
      {
        title: { sr: "Istorijat", en: "History" },
        body: {
          sr: "Kompaniju DeWalt je 1924. godine osnovao Raymond E. DeWalt u Leoli, Pensilvanija, poznat kao izumitelj radijalne testere. Njegov pronalazak imao je veliki uticaj na dalji razvoj elektri\u010dnih alata za obradu drveta.\n\nPoslovanje se brzo \u0161irilo, a kompanija je reorganizovana i ponovo registrovana 1947. kao DeWalt Inc. Godine 1949. preuzeo ju je American Machine & Foundry Co, koja ju je potom prodala kompaniji Black & Decker 1960. godine.\n\nBlack & Decker je 1989. godine prodao deo koji se bavio proizvodnjom radijalnih testera dvojici rukovodilaca, zadr\u017eavaju\u0107i fokus na drugim vrstama alata za profesionalce.\n\nU 1992. godini, Black & Decker je pokrenuo proces rebrendiranja svojih profesionalnih i naprednih alata pod imenom DeWalt alati. Ovaj potez je zna\u010dajno uticao na tr\u017ei\u0161te, jer je stvorio sna\u017ean brend fokusiran isklju\u010divo na alat za profesionalnu upotrebu.\n\nDeWalt je 1994. godine preuzeo nema\u010dkog proizvo\u0111a\u010da ELU i integrisao njegovu tehnologiju u svoj asortiman. Do 2001. godine, DeWalt je proizvodio i prodavao vi\u0161e od 200 modela stru\u010dnih alata i 800 dodataka.\n\nDeWalt je ubrzo postao prepoznatljiv me\u0111u komercijalnim izvo\u0111a\u010dima radova, naro\u010dito u gra\u0111evinskoj industriji. Godine 2004, Black & Decker je kupio konkurentskog proizvo\u0111a\u010da alata Porter-Cable i spojio ga sa DeWalt-om u D\u017eeksonu, Tenesi.\n\nU 2011. godini DeWalt je zapo\u010deo proizvodnju ru\u010dnih alata za izvo\u0111a\u010de, kao \u0161to su skalpeli, kle\u0161ta, podesivi klju\u010devi, metarski alati, testere i \u010deki\u0107i, koji su danas deo standardne opreme svakog majstora.\n\nDve godine kasnije, dodali su i alate za mehani\u010dare, uklju\u010duju\u0107i klju\u010deve, \u010degrtaljke i nastavke.\n\nU decembru 2013, DeWalt je najavio da \u0107e odre\u0111eni deo proizvoda sastavljati u Sjedinjenim Ameri\u010dkim Dr\u017eavama, koriste\u0107i komponente iz Brazila, Kine, \u010ce\u0161ke, Italije, Meksika, Velike Britanije i SAD.\n\nDo 2015. godine, kompanija je imala sedam proizvodnih pogona u SAD-u, \u0161to je oja\u010dalo poziciju DeWalt brenda kao ameri\u010dkog proizvo\u0111a\u010da alata.",
          en: "DeWalt was founded in 1924 by Raymond E. DeWalt in Leola, Pennsylvania, known as the inventor of the radial arm saw. His invention had a major impact on the development of electric woodworking tools.\n\nThe business expanded rapidly, and the company was reorganized and re-registered in 1947 as DeWalt Inc. In 1949, it was acquired by American Machine & Foundry Co, which later sold it to Black & Decker in 1960.\n\nIn 1989, Black & Decker sold the part of the business responsible for manufacturing radial saws to two company executives, while retaining a focus on other types of professional-grade tools.\n\nIn 1992, Black & Decker launched a rebranding initiative, introducing its professional and high-performance tools under the name DeWalt tools. This move significantly influenced the market by creating a strong brand focused on tools for professional use.\n\nIn 1994, DeWalt acquired the German manufacturer ELU and integrated its technology into its product lineup. By 2001, DeWalt was producing and selling over 200 models of professional tools and 800 accessories.\n\nDeWalt quickly became a favorite among commercial contractors, especially in the construction industry. In 2004, Black & Decker acquired rival tool manufacturer Porter-Cable and merged it with DeWalt in Jackson, Tennessee.\n\nIn 2011, DeWalt began producing hand tools for contractors, including utility knives, pliers, adjustable wrenches, measuring tools, saws, and hammers, all essential tools on a modern jobsite.\n\nTwo years later, they expanded into automotive tools, such as wrenches, ratchets, and sockets.\n\nIn December 2013, DeWalt announced that certain products would be assembled in the United States, using components sourced from Brazil, China, the Czech Republic, Italy, Mexico, the UK, and the US.\n\nBy 2015, the company operated seven manufacturing facilities in the U.S., reinforcing DeWalt's image as an American tool brand.",
        },
      },
      {
        title: { sr: "Tehnologije i inovacije", en: "Technologies and innovations" },
        body: {
          sr: "U aprilu 2016. godine, DeWalt je predstavio pametni telefon zasnovan na Android sistemu, razvijen posebno za radnike u gra\u0111evinskoj industriji. Ovaj ure\u0111aj je otporan na udarce i ekstremne uslove, \u0161to ga \u010dini savr\u0161enim za rad na gradili\u0161tima.\n\nSeptembra 2016. predstavljen je hibridni akumulator FlexVolt, koji mo\u017ee raditi na 60 V (54 V nominalno) i 2 Ah, ili na 20 V (18 V nominalno) i 6 Ah, u zavisnosti od vrste baterijskog alata.\n\nOko maja 2017. godine, DeWalt je po\u010deo da uklju\u010duje Bluetooth tehnologiju ToolConnect u svoje bu\u0161ilice i odvija\u010de. ToolConnect omogu\u0107ava korisnicima da preko mobilne aplikacije upravljaju svojim elektri\u010dnim alatima, prate njihov status i pode\u0161avaju funkcije.\n\nNeki modeli imaju ugra\u0111enu podr\u0161ku za ToolConnect, dok se kod drugih funkcionalnost mo\u017ee dodati naknadno pomo\u0107u dodatnog \u010dipa.\n\nU maju 2018. lansirana je linija be\u017ei\u010dnih kosilica na 20 V i 40 V, koja se brzo pozicionirala kao deo DeWalt linije alata za odr\u017eavanje dvori\u0161ta.\n\nU septembru 2022. godine, DeWalt je predstavio POWERSTACK tehnologiju baterija, postav\u0161i prvi proizvo\u0111a\u010d koji koristi litijum-jonske \u0107elije u obliku vre\u0107ice za bolje performanse i kompaktniji dizajn.",
          en: "In April 2016, DeWalt introduced a rugged Android-based smartphone, specially designed for the construction workforce. The device is built to survive a two-meter drop and operate in temperatures ranging from \u221220\u00b0C to 60\u00b0C, making it ideal for construction sites.\n\nIn September 2016, the company introduced the FlexVolt hybrid battery, capable of operating at 60V (54V nominal) and 2Ah, or at 20V (18V nominal) and 6Ah, depending on the cordless tool in use.\n\nAround May 2017, DeWalt began integrating Bluetooth-enabled ToolConnect technology into its drills and drivers. ToolConnect allows users to monitor, track, and configure their power tools through a mobile app.\n\nSome models include built-in support for ToolConnect, while others can be upgraded with an add-on chip.\n\nIn May 2018, DeWalt launched a line of cordless lawn mowers running on 20V and 40V, quickly gaining traction in the outdoor tools market.\n\nIn September 2022, DeWalt introduced POWERSTACK battery technology, becoming the first tool manufacturer to use pouch-style lithium-ion battery cells, which offer increased performance and a compact form.",
        },
      },
      {
        title: { sr: "Asortiman proizvoda", en: "Product range" },
        body: {
          sr: "Ova kompanija je poznata po \u0161irokom asortimanu elektri\u010dnih i ru\u010dnih alata, namenjenih gra\u0111evinskom, proizvodnom i stolarskom sektoru, kao i korisnicima koji se bave radovima u ku\u0107nim uslovima.\n\nDeWalt alati za profesionalce uklju\u010duju bu\u0161ilice, testere, brusilice, aku alate, kosilice, kao i bogat izbor dodatne opreme. Tako\u0111e, tu su i precizni ru\u010dni alati DeWalt poput kle\u0161ta, skalpela i \u010deki\u0107a.\n\nBlack & Decker je ranije bio poznat po lak\u0161im alatima i ku\u0107nim ure\u0111ajima, \u0161to nije odgovaralo zahtevima profesionalaca u gra\u0111evinarstvu. Pred kraj 1980-ih, Michael Hammes je predlo\u017eio strategiju nalik onoj koju je Honda koristila za ulazak na tr\u017ei\u0161te luksuznih automobila.\n\nKao rezultat toga, Black & Decker je odlu\u010dio da iskoristi manje poznato ime DeWalt za povratak na tr\u017ei\u0161te profesionalnih alata.\n\nNakon akvizicije 1960. godine, DeWalt je proizvodio razli\u010dite stacionarne elektri\u010dne alate. U 1992. godini lansirani su i ru\u010dni alati pod brendom DeWalt, koji su ranije bili deo linija Black & Decker Professional i Kodiak.\n\nTe linije su uskoro uga\u0161ene, a DeWalt je postao primarni brend profesionalnih alata. Istra\u017eivanja su pokazala da je \u010dak 70% korisnika u industriji prepoznalo naziv DeWalt kao sinonim za pouzdanost i kvalitet.",
          en: "DeWalt is known for a wide range of power and hand tools, designed for the construction, manufacturing, and woodworking sectors, as well as for advanced DIY users.\n\nTheir product lineup includes DeWalt power tools like drills, saws, grinders, and cordless equipment, in addition to high-quality DeWalt hand tools such as pliers, utility knives, and hammers.\n\nPreviously, Black & Decker was best known for lighter tools and household appliances, which didn\u2019t meet the demands of professional tradespeople. In the late 1980s, Michael Hammes proposed a strategy similar to Honda\u2019s luxury car brand approach.\n\nAs a result, Black & Decker used the lesser-known DeWalt name to re-enter the professional power tools market.\n\nAfter the 1960 acquisition, DeWalt produced various stationary electric tools. In 1992, the company introduced a new line of handheld tools under the DeWalt brand, which previously belonged to Black & Decker's \u201cProfessional\u201d and \u201cKodiak\u201d series.\n\nThese older lines were soon discontinued, and DeWalt emerged as the primary brand for professional-grade tools. Industry research showed that 70% of tradespeople recognized the DeWalt name as a symbol of reliability and performance.",
        },
      },
      {
        title: { sr: "Sponzorstva", en: "Sponsorships" },
        body: {
          sr: "Od jula 2021. godine, DeWalt je zvani\u010dni dobavlja\u010d alata i opreme za McLaren Formula 1 tim, \u0161to dodatno potvr\u0111uje njihovu posve\u0107enost preciznosti i vrhunskim performansama.\n\nTako\u0111e, DeWalt je 2022. godine potpisao ugovor o sponzorstvu sa fudbalskim klubom AFC Bournemouth, \u010dime je jo\u0161 jednom demonstrirao svoju prisutnost i van industrije alata, u svetu profesionalnog sporta.",
          en: "Since July 2021, DeWalt has been the official tool and equipment supplier for the McLaren Formula 1 team, further emphasizing the brand\u2019s commitment to precision and high-performance standards.\n\nIn 2022, DeWalt also signed a sponsorship deal with the English football club AFC Bournemouth, expanding its presence beyond the tools industry into the world of professional sports.",
        },
      },
    ],
    catalogs: [
      { name: "Dewalt najprodavanije 2023", pdfUrl: "https://drive.google.com/file/d/1RuMzUGAO4sBoTsBYby_-qGIo5jlFirfP/view?usp=share" },
      { name: "Dewalt ograni\u010deno izdanje", pdfUrl: "https://drive.google.com/file/d/13y1RuBHKXtsudGYMzIi67ym4w5rb3jew/view?usp=share" },
    ],
    color: "#ECFF44",
    storeUrl: "https://www.prodavnicaalata.rs/proizvodjaci/dewalt/",
  };
