import type { Brand } from "./types";

export const gtv: Brand = {
    slug: "gtv",
    name: "GTV",
    logoSrc: "/logos/gtv-logo.png",
    description: "GTV je poznata poljska marka koja se isti\u010de svojom ponudom visokokvalitetnih proizvoda za opremanje enterijera i razne projekte.",
    heroDescription: { sr: "GTV - Uvoznik za Srbiju", en: "GTV - Importer for Serbia" },
    paragraphs: [
      {
        title: { sr: "Istorijat", en: "History" },
        body: {
          sr: "Od male poljske firme, GTV je izrastao u me\u0111unarodno prepoznatog proizvo\u0111a\u010da name\u0161tajske galanterije i LED rasvete. Kompanija je poznata po brzoj operativnosti, inovativnosti i prilagodljivosti potrebama tr\u017ei\u0161ta. GTV ve\u0107 decenijama uspe\u0161no odgovara na dinami\u010dno promenljive zahteve kupaca i pa\u017eljivo prati globalne trendove u oblasti enterijera, okova i LED osvetljenja.\n\nTokom 2022. godine, GTV je pro\u0161irio svoje poslovanje kupovinom pogona specijalizovanog za proizvodnju ramova za krevete, okvira, dovratnika, mehanizama i dodataka za tapacirani name\u0161taj. Ovaj proizvodni centar u \u0160\u010ditnu predstavlja strate\u0161ki korak ka ja\u010danju prisustva u komplementarnim segmentima tr\u017ei\u0161ta name\u0161taja. Ovim potezom GTV dodatno diversifikuje svoju ponudu i omogu\u0107ava kupcima \u0161iri izbor proizvoda za savremeno opremanje prostora.\n\nVrednosti kao \u0161to su po\u0161tenje, otvorenost, profesionalizam i podr\u0161ka \u010dine temelj organizacione kulture kompanije GTV, \u0161to dodatno u\u010dvr\u0161\u0107uje poverenje kupaca i partnera \u0161irom Evrope i sveta.",
          en: "From a small Polish company, GTV has grown into an internationally recognized manufacturer of furniture fittings and LED lighting. The company is known for its fast operations, innovation, and ability to adapt to market demands. For decades, GTV has successfully responded to rapidly changing customer needs while closely monitoring global trends in interior design, hardware solutions, and LED technologies.\n\nIn 2022, GTV expanded its business by acquiring a production facility specialized in manufacturing bed frames, door frames, casings, mechanisms, and accessories for upholstered furniture. Located in Szczytno, this production center represents a strategic move to strengthen GTV\u2019s presence in complementary segments of the furniture market. This investment allows GTV to diversify its offering and provide customers with a broader range of products for modern space solutions.\n\nCore values such as honesty, transparency, professionalism, and support form the foundation of GTV\u2019s organizational culture, further reinforcing the trust of customers and partners across Europe and around the world.",
        },
      },
      {
        title: { sr: "Tehnologije i inovacije", en: "Technologies and innovations" },
        body: {
          sr: "GTV konstantno ula\u017ee u savremene tehnologije i vrhunske materijale, kako bi njihovi okovi za name\u0161taj i LED rasveta zadovoljili najvi\u0161e standarde kvaliteta i estetike. Njihovi proizvodi se oslanjaju na inovacije koje prate najnovije trendove u dizajnu enterijera i pametnim re\u0161enjima za ure\u0111enje doma i poslovnog prostora.\n\nKao istinski preduzetnici, stru\u010dnjaci u GTV-u neprestano u\u010de i razvijaju nove ve\u0161tine, a svoju stru\u010dnost primenjuju kroz stvaranje proizvoda koji zadovoljavaju i trenutne i budu\u0107e potrebe tr\u017ei\u0161ta. Zahvaljuju\u0107i naprednim re\u0161enjima kao \u0161to su cloud computing, ve\u0161ta\u010dka inteligencija i automatizovani alati, GTV razvija pametne sisteme koji unapre\u0111uju korisni\u010dko iskustvo.\n\nKroz optimizaciju logisti\u010dkih procesa, GTV osigurava visoku dostupnost celokupnog asortimana, od LED traka do okova za ormare, kliznih sistema i dodataka za kuhinje i dnevne sobe.",
          en: "GTV continuously invests in cutting-edge technologies and high-quality materials to ensure their furniture fittings and LED lighting meet the highest standards of quality and design. Their products are built on innovations that follow the latest trends in interior aesthetics and smart solutions for both residential and commercial spaces.\n\nAs true entrepreneurs, the experts at GTV constantly learn, develop new skills, and apply their knowledge to create products that meet both current and future market demands. By leveraging advanced technologies such as cloud computing, artificial intelligence, and automation tools, GTV delivers intelligent systems that enhance the overall user experience.\n\nThrough the optimization of logistics processes, GTV guarantees high availability of its full product range, from LED strips and profiles to cabinet hinges, sliding systems, and kitchen accessories.",
        },
      },
      {
        title: { sr: "Asortiman proizvoda", en: "Product range" },
        body: {
          sr: "GTV nudi jedan od najkompletnijih asortimana name\u0161tajske galanterije i LED rasvete na tr\u017ei\u0161tu. Njihova ponuda uklju\u010duje okove za name\u0161taj, kliza\u010de, \u0161arke, podizne mehanizme, ru\u010dke, dugmad, LED trake, aluminijumske profile i dodatke za osvetljenje. Ovi proizvodi omogu\u0107avaju savr\u0161enu zavr\u0161nu obradu, tihi rad fioka i vrata, kao i maksimalnu funkcionalnost u ograni\u010denom prostoru.\n\nInovativna re\u0161enja za u\u0161tedu prostora i ergonomiju doprinose modernom dizajnu enterijera, a brojni GTV proizvodi zadovoljavaju potrebe kako profesionalnih stolara, tako i hobista koji \u017eele kvalitetne i estetski privla\u010dne elemente za svoj name\u0161taj.\n\nPortfelj kompanije broji vi\u0161e od 12.000 proizvoda, uklju\u010duju\u0107i LED rasvetu, fitinge, dodatke za kuhinje, okove za garderobere i jo\u0161 mnogo toga. Ova raznovrsnost omogu\u0107ava kupcima da prona\u0111u sve potrebne komponente za projekat na jednom mestu, \u0161tede\u0107i vreme, trud i novac.\n\nSlogan \u201eKreiramo bolji svakodnevni \u017eivot za ljude\u201c oslikava njihovu posve\u0107enost stvaranju proizvoda koji ne samo da izgledaju moderno, ve\u0107 i \u010dine \u017eivot lak\u0161im i funkcionalnijim.",
          en: "GTV offers one of the most comprehensive assortments of furniture fittings and LED lighting solutions available on the market. Their extensive portfolio includes cabinet hardware, drawer slides, hinges, lift systems, handles, knobs, LED strips, aluminum profiles, and various lighting accessories. These products provide perfect finishing touches, quiet drawer and door movement, and optimal functionality in limited spaces.\n\nInnovative space-saving and ergonomic solutions contribute to modern interior design. Many GTV products are designed to meet the expectations of both professional carpenters and hobbyists who value high-quality and visually appealing components for their furniture.\n\nThe company\u2019s catalog includes more than 12,000 products, covering everything from lighting and fittings to kitchen accessories and wardrobe systems. This extensive offering allows customers to find everything they need for their projects in one place, saving time, effort, and resources.\n\nThe motto \u201cCreating a better everyday life for people\u201d reflects GTV\u2019s strong commitment to developing products that not only look great but also make everyday living simpler and more functional.",
        },
      },
      {
        title: { sr: "Podr\u0161ka", en: "Customer support" },
        body: {
          sr: "Zadovoljan kupac je glavni prioritet kompanije GTV. Zato nude sveobuhvatnu korisni\u010dku podr\u0161ku tokom cele saradnje, od izbora name\u0161tajskih okova do instalacije LED rasvete. Tim stru\u010dnjaka pru\u017ea pomo\u0107 u odabiru optimalnog re\u0161enja, brzo procesira porud\u017ebine i organizuje efikasnu isporuku.\n\nGTV podr\u017eava svoje B2B partnere kroz pouzdanu platformu, tehni\u010dku dokumentaciju, vizualizacije i marketin\u0161ke materijale. Njihovi savetnici su eksperti u oblasti name\u0161tajske galanterije i LED osvetljenja, a govore vi\u0161e jezika, kako bi komunikacija sa kupcima iz razli\u010ditih zemalja bila \u0161to jednostavnija.\n\nPoslovni partneri mogu ra\u010dunati na personalizovanu marketin\u0161ku podr\u0161ku, savete o asortimanu i znanje o tr\u017ei\u0161nim trendovima. GTV ne samo da prodaje proizvode, oni grade dugoro\u010dne odnose sa svojim klijentima i doprinose uspehu svakog projekta.",
          en: "Customer satisfaction is GTV\u2019s top priority. That\u2019s why they provide full customer support throughout the entire purchasing process, from selecting the right furniture fittings to installing LED lighting. Their team of experienced specialists offers assistance in choosing the best solutions, processes orders promptly, and ensures efficient delivery logistics.\n\nGTV supports its B2B partners with a reliable online platform, technical documentation, 3D visualizations, and a wide array of marketing materials. Their advisors are experts in the fields of furniture fittings and LED lighting and are fluent in multiple languages to ensure smooth communication with international clients.\n\nEvery business partner can count on personalized marketing support, product range consulting, and valuable insights into market trends. GTV doesn\u2019t just sell products, they build long-term relationships and contribute to the success of every project.",
        },
      },
    ],
    catalogs: [
      { name: "GTV katalog", pdfUrl: "https://drive.google.com/file/d/1O7cEdZPw2CyvNTsxmfR7ZpL9GAXlpJ5k/view?usp=share" },
    ],
    color: "#845EC2",
    storeUrl: "https://www.prodavnicaalata.rs/proizvodjaci/gtv/",
  };
