import type { Brand } from "./types";

export const karcher: Brand = {
    slug: "karcher",
    name: "K\u00e4rcher",
    logoSrc: "/logos/karcher-logo.svg",
    description: "K\u00e4rcher je svetski poznati proizvo\u0111a\u010d visokokvalitetnih \u010dista\u010da za doma\u0107instvo i industriju sa inovativnim tehnologijama i visokim standardima.",
    heroDescription: { sr: "K\u00e4rcher - Uvoznik za Srbiju", en: "K\u00e4rcher - Importer for Serbia" },
    paragraphs: [
      {
        title: { sr: "Istorijat", en: "History" },
        body: {
          sr: "Nakon \u0161to je diplomirao na Tehni\u010dkom univerzitetu u \u0160tutgartu 1924. godine, Alfred K\u00e4rcher (1901\u20131959) pridru\u017eio se porodi\u010dnom biznisu koji se bavio prodajom industrijske opreme za kuvanje i pranje u delu \u0160tutgarta zvanom Bad Kan\u0161tat.\n\nTokom narednih godina, Alfred K\u00e4rcher je razvio niz tehni\u010dkih re\u0161enja, uklju\u010duju\u0107i elektri\u010dne uranjaju\u0107e greja\u010de i industrijske pe\u0107i za sagorevanje, \u010dime je postavio temelje za osnivanje sopstvene kompanije.\n\nGodine 1935. osnovao je Alfred K\u00e4rcher Komanditno dru\u0161tvo, a ve\u0107 1939. kompanija, tada sa 120 zaposlenih, preselila se u Vinneneden, gde se i danas nalazi sedi\u0161te.\n\nU tom periodu, firma je proizvodila proizvode kao \u0161to su \u0161poreti, kolica i greja\u010di, dok su se tokom obnove posleratnih gradova pojavili i prvi K\u00e4rcher greja\u010di za betonske oplate i sve\u017e vazduh.\n\nOd 1950-ih do 1970-ih, fokus je bio na proizvodnji industrijskih parnih generatora i grejalica, dok su tehnologije za \u010di\u0161\u0107enje tek kasnije postale glavni izvor prihoda.\n\nNakon smrti Alfreda K\u00e4rchera 1959. godine, njegovu ulogu preuzima supruga Irene K\u00e4rcher, koja je u prvoj godini upravljanja pove\u0107ala prihode za 70%.\n\nKompanija se brzo internacionalizuje 1962. osniva prodajnu firmu u Francuskoj, a ubrzo zatim i u Austriji i \u0160vajcarskoj.\n\nTokom 1970-ih, K\u00e4rcher menja korporativnu boju iz plave u \u017eutu i u potpunosti se fokusira na visokotla\u010dne \u010dista\u010de, zapo\u010dev\u0161i globalnu proizvodnju otvaranjem fabrike u Brazilu.\n\nGodine 1984. na tr\u017ei\u0161te je lansiran prvi visokotla\u010dni \u010dista\u010d za ku\u0107nu upotrebu, \u0161to ozna\u010dava po\u010detak nove ere za K\u00e4rcher, razvoj profesionalne opreme za \u010di\u0161\u0107enje i \u0161irenje portfolija.\n\nDo kraja 1980-ih, kompanija je uklju\u010dena u projekte \u010di\u0161\u0107enja istorijskih zgrada \u0161irom sveta.\n\nU 1990-im godinama, K\u00e4rcher se pro\u0161irio na komercijalno \u010di\u0161\u0107enje podova i razvio brojne aparate za ku\u0107nu i profesionalnu upotrebu, uklju\u010duju\u0107i usisiva\u010de i paro\u010dista\u010de.\n\nGodine 2003. predstavljen je prvi autonomni \u010dista\u010d za potro\u0161a\u010de, dok su u narednim godinama razvijani roboti i ba\u0161tenska oprema kao \u0161to su pumpe i prskalice.\n\nNa kraju 2011. godine, kupljena je biv\u0161a Pfleiderer fabrika, \u010dime je gotovo udvostru\u010dena operativna povr\u0161ina.\n\nU 2022. godini, K\u00e4rcher lansira Kira prvi autonomni usisiva\u010d i brisa\u010d za profesionalnu upotrebu.",
          en: "After graduating from the Technical University of Stuttgart in 1924, Alfred K\u00e4rcher (1901\u20131959) joined the family business, which sold industrial cooking and washing equipment in Bad Cannstatt, a district of Stuttgart.\n\nIn the following years, he began developing devices such as electric immersion heaters and combustion furnaces for industrial use, laying the foundation for his own company.\n\nIn 1935, he founded Alfred K\u00e4rcher Limited Partnership in Bad Cannstatt.\n\nDue to space constraints, 120 employees moved to Winnenden in 1939, where the company\u2019s headquarters remain today.\n\nBy the late 1940s, K\u00e4rcher was producing items like stoves, handcarts, and trailers for civilians.\n\nThe company also manufactured concrete formwork heaters and air heaters for post-war reconstruction.\n\nFrom the 1950s to the 1970s, K\u00e4rcher focused on producing steam generators for industry and construction, while cleaning technology became the company\u2019s main revenue stream later.\n\nOn September 17, 1959, Alfred K\u00e4rcher passed away at age 58 from a heart attack.\n\nHis wife, Irene K\u00e4rcher (1920\u20131989), took over the business, increasing revenue by 70% in the first year.\n\nBy 1962, K\u00e4rcher had opened its first sales office outside Germany, near Paris, followed by branches in Austria and Switzerland.\n\nIn the 1960s and 1970s, K\u00e4rcher expanded into the global market, producing toys, catamarans, and construction formwork before focusing on high-pressure cleaners in 1974.\n\nThat year, the corporate color changed from blue to yellow, and the first international factory was opened in Brazil.\n\nFrom the late 1970s, K\u00e4rcher began cleaning historical monuments worldwide.\n\nIn 1984, it launched its first high-pressure cleaner for home use.\n\nAfter Irene K\u00e4rcher passed away in 1989, management was taken over by the existing executive team.\n\nAlfred and Irene K\u00e4rcher\u2019s descendants remained involved in supervisory roles.\n\nDuring the 1990s, K\u00e4rcher entered the commercial floor-cleaning and municipal equipment sector.\n\nThe company launched household appliances like vacuum cleaners and steam cleaners.\n\nIn 2003, K\u00e4rcher introduced its first fully autonomous consumer cleaner and later expanded into gardening with pumps and watering systems.\n\nBy the end of 2011, K\u00e4rcher acquired the former Pfleiderer factory in Winnenden, nearly doubling its operational space.\n\nIn 2022, K\u00e4rcher released Kira, the first autonomous vacuum and mop for professional use.",
        },
      },
      {
        title: { sr: "Tehnologije i inovacije", en: "Technologies and innovations" },
        body: {
          sr: "K\u00e4rcher konstantno ula\u017ee u razvoj naprednih tehnologija za \u010di\u0161\u0107enje.\n\nAutomatizovani sistemi i digitalni alati omogu\u0107avaju preciznu kontrolu proizvodnje i efikasno otkrivanje problema.\n\nKompanija razvija pametne ure\u0111aje povezive sa internetom, sa naprednim senzorima i softverskim re\u0161enjima za optimizaciju rada.\n\nInovacije poput smanjenja potro\u0161nje energije, upotrebe naprednih litijum-jonskih baterija i be\u017ei\u010dne tehnologije doprinele su efikasnosti njihovih ure\u0111aja.\n\nK\u00e4rcher \u010dista\u010di pod pritiskom, profesionalni usisiva\u010di i ure\u0111aji za parno \u010di\u0161\u0107enje sve vi\u0161e koriste automatizaciju i IoT tehnologiju.\n\nJedan od ranih uspeha bio je energetski efikasni ure\u0111aj za industrijsko kupanje u slanoj vodi.\n\nPatent za ovu tehnologiju prodat je Siebert GmbH, a do kraja rata prodat je u vi\u0161e od 1.200 primeraka.\n\nU 2024. godini, prema izve\u0161taju WIPO, K\u00e4rcher je bio me\u0111u top 10 kompanija u svetu po broju registrovanih industrijskih dizajna, sa ukupno 189 dizajna prijavljenih tokom 2023. godine.",
          en: "K\u00e4rcher constantly integrates modern technology to improve the efficiency of its cleaning equipment.\n\nAutomated systems allow for precise production control, while digital tools help monitor performance and quickly identify issues.\n\nSmart cleaning devices that can connect to the internet enable remote operation and monitoring.\n\nThe use of advanced sensors and software ensures accurate analysis and predictive maintenance.\n\nEnergy-efficient innovations and optimized resource usage contribute to greater sustainability and productivity.\n\nOne of K\u00e4rcher\u2019s early commercial successes was a salt bath furnace used for hardening and refining light metals.\n\nThe patent was sold to Siebert GmbH, with over 1,200 units sold by 1945.\n\nAccording to WIPO\u2019s 2024 annual report, K\u00e4rcher ranked 10th globally in industrial design with 189 registrations in 2023.",
        },
      },
      {
        title: { sr: "Asortiman proizvoda", en: "Product range" },
        body: {
          sr: "K\u00e4rcher nudi bogat izbor opreme za \u010di\u0161\u0107enje, uklju\u010duju\u0107i \u010dista\u010de pod pritiskom, industrijske usisiva\u010de, parne \u010dista\u010de i ure\u0111aje za odr\u017eavanje podova i fasada.\n\nNjihovi visokotla\u010dni \u010dista\u010di su klju\u010dni proizvodi, idealni za uklanjanje tvrdokornih prljav\u0161tina sa betona, plo\u010dica, kamena i drugih povr\u0161ina.\n\nAsortiman obuhvata profesionalne usisiva\u010de za suvo i mokro \u010di\u0161\u0107enje, kao i komercijalne modele za fabrike, skladi\u0161ta i kancelarije.\n\nK\u00e4rcher paro\u010dista\u010di koriste paru za dezinfekciju, uklanjaju\u0107i ne\u010disto\u0107e bez hemikalija, \u0161to ih \u010dini idealnim za doma\u0107instva i zdravstvene ustanove.\n\nU ponudi su i sistemi za \u010di\u0161\u0107enje podova velikih povr\u0161ina, kao i specijalizovani ure\u0111aji za pranje prozora i fasada.\n\nKompanija je poznata po kvalitetu i pouzdanosti, \u010dine\u0107i K\u00e4rcher idealnim izborom kako za profesionalce, tako i za privatne korisnike koji tra\u017ee vrhunske aparate za \u010di\u0161\u0107enje.",
          en: "K\u00e4rcher offers an extensive range of cleaning equipment for industrial and commercial use.\n\nTheir catalog includes pressure washers, vacuum cleaners, steam cleaners, and specialized equipment for floor and glass cleaning.\n\nHigh-pressure washers are K\u00e4rcher\u2019s flagship products, using powerful water jets to remove stubborn dirt from concrete, stone, and tiled surfaces.\n\nTheir vacuum cleaners are designed for both household and commercial applications, capable of handling dry, wet, and specific types of waste.\n\nK\u00e4rcher\u2019s steam cleaners disinfect and clean various surfaces without chemicals, making them ideal for homes and healthcare facilities.\n\nIn addition, K\u00e4rcher offers floor cleaning machines for large industrial spaces and specialized tools for cleaning glass surfaces and facades, delivering fast and efficient maintenance solutions.",
        },
      },
    ],
    catalogs: [
      { name: "Karcher profesionalni program katalog", pdfUrl: "https://drive.google.com/file/d/1rCZ63RGygIn4IeTTar4sLetDzc7UUoaJ/view?usp=share" },
      { name: "Karcher \u017euti program katalog", pdfUrl: "https://drive.google.com/file/d/14ERZxuCZexyQZ0rNtbBUXGXKjzZm_x5Q/view?usp=share" },
    ],
    color: "#ECFF44",
    storeUrl: "https://www.prodavnicaalata.rs/proizvodjaci/karcher/",
  };
