import type { Brand } from "./types";

export const knipex: Brand = {
    slug: "knipex",
    name: "Knipex",
    logoSrc: "/logos/knipex-logo.svg",
    description: "Knipex je vode\u0107i proizvo\u0111a\u010d visokokvalitetnih ru\u010dnih alata specijalizovanih za rad sa cevima, \u017eicama i sli\u010dnim materijalima.",
    heroDescription: { sr: "Knipex alati - Uvoznik za Srbiju", en: "Knipex Tools - Importer for Serbia" },
    paragraphs: [
      {
        title: { sr: "Istorijat", en: "History" },
        body: {
          sr: "Knipex je ve\u0107 \u010detiri generacije nezavisno, porodi\u010dno preduze\u0107e sa sedi\u0161tem u Kronenbergu, Vupertal, u srcu nema\u010dke industrije alata. Poznat po vrhunskim kle\u0161tima i specijalizovanim ru\u010dnim alatima, Knipex proizvodi sve osnovne artikle, uklju\u010duju\u0107i kvalitetna kle\u0161ta i profesionalne alate, isklju\u010divo u Nema\u010dkoj. Pojedini dodatni alati, poput pinceta i ko\u017enih torbi za alat sa Knipex brendom, dolaze od pa\u017eljivo odabranih eksternih dobavlja\u010da.\n\nKompanija je osnovana 1882. godine kao mala kova\u010dnica koju je pokrenuo Karl Gustav Pu\u010d u podrumu svoje porodi\u010dne ku\u0107e. Po\u010deli su sa samo jednim radnikom i dva pripravnika, a ve\u0107 tada se fokusirali na proizvodnju kle\u0161ta za tesare i potkiva\u010de. Ta kle\u0161ta su se u po\u010detku izra\u0111ivala ru\u010dno, ali je ubrzo usledila modernizacija uz upotrebu \u010deki\u0107a za kovanje. Na vrhuncu pod vo\u0111stvom Karla Pu\u010da, proizvodilo se \u010dak 7.000 pari kle\u0161ta nedeljno.\n\nKnipex je 1942. zvani\u010dno za\u0161titio svoj brend, a nova generacija porodice Pu\u010d nastavila je razvoj. Godine 1954, tre\u0107a generacija, Karl Pu\u010d, preuzima vo\u0111enje firme i uvodi automatizaciju, inovacije i patente u proizvodni proces. Od 1996. godine, firmu vodi Ralf Pu\u010d, praunuk osniva\u010da, koji je pro\u0161irio prisustvo Knipex alata na vi\u0161e od deset zemalja \u0161irom sveta. Danas se vi\u0161e od 60% proizvodnje izvozi, \u0161to govori o globalnom ugledu koji Knipex u\u017eiva kao lider u proizvodnji kle\u0161ta i alata za elektri\u010dare, vodoinstalatere i druge zanatlije.",
          en: "Knipex is a fourth-generation, family-owned and independent company based in Cronenberg, Wuppertal, located in the heart of Germany\u2019s tool manufacturing region. Renowned for its high-quality pliers and specialized hand tools, Knipex produces all core items, including premium pliers and professional tools, exclusively in Germany. Certain additional tools, such as tweezers and branded leather tool bags, are sourced from carefully selected external suppliers.\n\nThe company was founded in 1882 as a small forge by Carl Gustav Putsch in the basement of his family home. It began with just one worker and two apprentices, focusing from the start on manufacturing pliers for carpenters and farriers. These pliers were initially made by hand, but modernization quickly followed with the introduction of power hammers. At its peak under Carl Putsch\u2019s leadership, the company was producing as many as 7,000 pairs of pliers per week.\n\nKnipex officially registered its brand in 1942, and the next generation of the Putsch family continued the company\u2019s growth. In 1954, the third generation, led by Karl Putsch, took over the business, introducing automation, innovation, and patents into the manufacturing process. Since 1996, the company has been headed by Ralf Putsch, great-grandson of the founder, who has expanded the Knipex presence to more than ten countries worldwide. Today, over 60% of production is exported, demonstrating the brand\u2019s global reputation as a leading manufacturer of pliers and tools for electricians, plumbers, and professional craftsmen.",
        },
      },
      {
        title: { sr: "Tehnologije i inovacije", en: "Technologies and innovations" },
        body: {
          sr: "Knipex se izdvaja kao brend koji neprekidno pomera granice u razvoju ru\u010dnih alata. Njihovi alati, posebno Cobra kle\u0161ta sa sistemom za brzo pode\u0161avanje jednom rukom, predstavljaju spoj funkcionalnosti i preciznosti. Cobolt seka\u010di su jo\u0161 jedan primer inovacije, kompaktni, ali izuzetno mo\u0107ni alati za se\u010denje zavrtnjeva i tvrdih materijala. Kle\u0161ta-klju\u010devi kombinuju funkcije vilju\u0161kastog klju\u010da i standardnih kle\u0161ta, nude\u0107i korisnicima alat visoke preciznosti i izdr\u017eljivosti.\n\nOva tehnolo\u0161ka re\u0161enja \u010dine Knipex alatima sinonimom za profesionalne performanse u svim granama industrije, naro\u010dito u elektroinstalacijama, odr\u017eavanju, monta\u017ei solarnih sistema i drugim specijalizovanim poslovima.",
          en: "Knipex stands out as a brand that continuously pushes the boundaries in hand tool development. Their tools, especially the Cobra pliers with one-handed quick adjustment, represent a perfect blend of functionality and precision. The Cobolt cutters are another innovation, compact yet extremely powerful tools capable of cutting bolts and tough materials. Pliers wrenches combine the functionality of an adjustable wrench and standard pliers, offering users a high-precision, durable solution.\n\nThese advanced designs make Knipex tools synonymous with professional performance across all industries, especially in electrical installations, maintenance, solar system assembly, and other specialized technical fields.",
        },
      },
      {
        title: { sr: "Asortiman proizvoda", en: "Product range" },
        body: {
          sr: "Knipex katalog sadr\u017ei oko 100 razli\u010ditih modela kle\u0161ta, sa vi\u0161e od 900 varijacija u du\u017eini, obliku dr\u0161ke i zavr\u0161noj obradi. U ponudi su bo\u010dni seka\u010di, kle\u0161ta za elektri\u010dare, vodoinstalaterska kle\u0161ta, kao i visoko specijalizovani alati za elektroniku i precizne poslove. Alati za elektri\u010dare uklju\u010duju re\u0161enja za se\u010denje kablova, skidanje izolacije i krimpovanje \u017eica, sve uz maksimalnu ergonomiju i sigurnost.\n\nVe\u0107ina modela dostupna je i u varijantama sa izolovanim dr\u0161kama, koje \u0161tite od elektri\u010dnog napona do 1.000 V, \u0161to ih \u010dini neophodnim izborom za sve profesionalce u elektroindustriji. Sistem ozna\u010davanja alata koristi decimalnu \u0161ifru koja sadr\u017ei informacije o tipu kle\u0161ta, obliku vilica i veli\u010dini alata, \u0161to korisnicima olak\u0161ava izbor pravog modela.\n\nKnipex se oslanja na sopstvenu proizvodnju, sa internim procesima koji obuhvataju sve faze, od kovanja, bu\u0161enja, glodanja i bru\u0161enja do laserske obrade, \u010dime se osigurava vrhunski kvalitet svakog komada.",
          en: "The Knipex catalog features around 100 different plier models, with over 900 variations in size, handle design, and finish. The range includes side cutters, electrician\u2019s pliers, water pump pliers, and highly specialized tools for electronics and precision work. Electrician\u2019s tools include cable cutters, wire strippers, and crimping tools, engineered for maximum ergonomics and safety.\n\nMost models are available in insulated versions, tested to withstand electrical voltage up to 1,000 V, making them an essential choice for professionals in the electrical industry. The tool classification system uses a decimal code that provides information about the type of pliers, jaw design, and size, helping users easily identify the right model.\n\nKnipex relies entirely on in-house production, with internal processes covering all stages, from forging, drilling, and milling to grinding and laser processing, ensuring top-level quality in every product.",
        },
      },
      {
        title: { sr: "Knipex muzej", en: "Knipex museum" },
        body: {
          sr: "U sedi\u0161tu firme u Vupertalu nalazi se Knipex muzej, posve\u0107en istoriji ru\u010dnih alata i razvoja alata kroz vreme. Na dva sprata, posetioci mogu videti alate, ma\u0161ine, rekonstruisana radna mesta i predmete iz svakodnevnog \u017eivota koji oslikavaju bogatu tradiciju nema\u010dke alatni\u010darske industrije.\n\nMuzej je otvoren za javnost jednom godi\u0161nje tokom manifestacije Wuppertal-24h-live, dok su grupne posete mogu\u0107e uz prethodnu najavu tokom cele godine.",
          en: "The Knipex Museum, located at the company\u2019s headquarters in Wuppertal, is dedicated to the history and evolution of hand tools over time. Spread over two floors, visitors can explore tools, machines, reconstructed workstations, and everyday items that illustrate the rich tradition of German toolmaking.\n\nThe museum is open to the public once a year during the Wuppertal-24h-live event, while group tours can be arranged by appointment throughout the year.",
        },
      },
    ],
    catalogs: [
      { name: "Knipex katalog", pdfUrl: "https://drive.google.com/file/d/1YgRP6jOCM6D4apCU-mRM_3mNn2yWiTpN/view?usp=share" },
    ],
    color: "#FF0000",
    storeUrl: "https://www.prodavnicaalata.rs/proizvodjaci/knipex/",
  };
