import type { Brand } from "./types";

export const max: Brand = {
    slug: "max",
    name: "MAX",
    logoSrc: "/logos/max-logo.svg",
    description: "MAX je poznata marka koja se specijalizuje za proizvodnju vrhunskih alata i ma\u0161ina, uklju\u010duju\u0107i pneumatske alate i klamerice.",
    heroDescription: { sr: "MAX alati - Uvoznik za Srbiju", en: "MAX Tools - Importer for Serbia" },
    paragraphs: [
      {
        title: { sr: "Istorijat", en: "History" },
        body: {
          sr: "Kompanija MAX je osnovana 1942. godine pod nazivom Yamada Air Industry Co., Ltd., a 1945. godine je zapo\u010dela proizvodnju poslovne i kancelarijske opreme.\n\nTokom 1964. godine, spajanjem proizvodnog i prodajnog sektora, formirana je kompanija MAX CO., LTD.\n\nOd tada, MAX se razvijao u prepoznatljivog proizvo\u0111a\u010da industrijske opreme i alata za gra\u0111evinsku industriju.\n\nKompanija se kotirala na Tokijskoj berzi 1970. godine, a glavno sedi\u0161te je 1981. preme\u0161teno u Tokio.\n\nTokom 1990-ih i 2000-ih godina, MAX je otvorio nove proizvodne pogone u Japanu, Kini, Tajlandu i Maleziji.\n\nParalelno sa \u0161irenjem, kompanija je uvela me\u0111unarodno priznate ISO sertifikate za upravljanje kvalitetom (ISO9001) i za\u0161titom \u017eivotne sredine (ISO14001), \u010dime je dodatno u\u010dvrstila svoj status lidera u industriji alata.\n\nGodine 2010. i 2014. MAX je izvr\u0161io strate\u0161ke akvizicije i osnovao nova predstavni\u0161tva u Aziji i Evropi, pro\u0161iruju\u0107i prisustvo na globalnom tr\u017ei\u0161tu.\n\nKroz decenije rada, MAX konstantno ja\u010da istra\u017eiva\u010dke kapacitete i razvija proizvode koji zadovoljavaju visoke standarde profesionalaca \u0161irom sveta.\n\nMAX je danas me\u0111unarodno prepoznat kao pouzdan proizvo\u0111a\u010d industrijskih alata, kancelarijske opreme i elektri\u010dnih alata.\n\nNjihovi razvojni timovi kreiraju proizvode sa originalnim i izdr\u017eljivim karakteristikama, koji odgovaraju na potrebe profesionalnih korisnika u razli\u010ditim industrijama.",
          en: "Founded in 1942 under the name Yamada Air Industry Co., Ltd., MAX began manufacturing business and office equipment in 1945.\n\nIn 1964, the integration of production and sales sectors led to the formation of MAX CO., LTD.\n\nSince then, MAX has grown into a globally recognized manufacturer of industrial tools and equipment for the construction industry.\n\nThe company was listed on the Tokyo Stock Exchange in 1970, and the headquarters moved to Tokyo in 1981.\n\nDuring the 1990s and 2000s, MAX expanded its manufacturing capabilities with new plants in Japan, China, Thailand, and Malaysia.\n\nIt also introduced ISO9001 and ISO14001 certifications, reinforcing its commitment to quality and environmental responsibility.\n\nIn 2010 and 2014, key acquisitions and the establishment of new offices across Asia and Europe allowed MAX to further expand its global footprint.\n\nOver the decades, MAX has strengthened its R&D capabilities, becoming a leading developer of tools that meet the evolving needs of professionals worldwide.\n\nToday, MAX is internationally recognized as a reliable manufacturer of industrial equipment, office solutions, and power tools.\n\nIts product development teams focus on creating durable and innovative tools that cater to the demands of various industries.",
        },
      },
      {
        title: { sr: "Tehnologije i inovacije", en: "Technologies and innovations" },
        body: {
          sr: "Inovacije u kompaniji MAX zapo\u010dinju u istra\u017eiva\u010dkim, dizajnerskim i proizvodnim odeljenjima, a zavr\u0161avaju se kod krajnjih korisnika koji koriste MAX alate u svakodnevnom radu.\n\nNa osnovu povratnih informacija sa tr\u017ei\u0161ta, proizvodi se neprekidno prilago\u0111avaju stvarnim uslovima rada.\n\nBliska saradnja sa korisnicima omogu\u0107ava kompaniji da prati tehnolo\u0161ke trendove i predvidi budu\u0107e potrebe u gra\u0111evinskoj i industrijskoj proizvodnji.\n\nMAX alati se razvijaju u Japanu i proizvode u pogonima sa ISO sertifikatima, garantuju\u0107i visoku pouzdanost i kvalitet.\n\nSvaki proizvod prolazi rigorozne testove kako bi zadovoljio interne standarde kvaliteta i izdr\u017eljivosti.\n\nStalnim ulaganjem u istra\u017eivanje i razvoj, MAX doprinosi stvaranju pametnih alata i re\u0161enja koja zna\u010dajno olak\u0161avaju rad na gradili\u0161tu, u proizvodnim halama i kancelarijskom okru\u017eenju.",
          en: "Innovation at MAX begins in the research, design, and production departments and ends with the end-user.\n\nBased on user feedback, MAX tools are regularly optimized for real-world conditions.\n\nClose collaboration with customers enables the company to stay ahead of emerging trends and anticipate industry developments.\n\nMAX tools are developed in Japan and produced in ISO-certified factories, ensuring reliability and premium quality.\n\nAll products undergo rigorous testing to meet internal standards.\n\nContinuous investment in R&D allows MAX to design smart tools and advanced solutions that make work on-site and in the workshop easier and more efficient.",
        },
      },
      {
        title: { sr: "Asortiman proizvoda", en: "Product range" },
        body: {
          sr: "MAX je postao sinonim za inovacije u oblasti alata, bio je prvi na svetu koji je razvio eksericu za krovove (1982), baterijski alat za vezivanje armature (1993), kao i kompresore i pneumatske ekserice visokog pritiska (1994).\n\nOvi alati su prepoznati me\u0111u profesionalcima zbog svoje pouzdanosti, dugotrajnosti i ergonomije.\n\nIndustrijski alati MAX uklju\u010duju \u010dvrste, ali lagane ure\u0111aje specijalno razvijene za primenu u gra\u0111evinskoj industriji.\n\nAsortiman obuhvata pneumatske ekserice, kompresore visokog pritiska (do 20 bara), alate za metal i beton, kao i dodatke za efikasno izvo\u0111enje radova na terenu.\n\nKancelarijska divizija kompanije MAX nudi \u0161irok spektar ure\u0111aja, me\u0111u kojima su poznate heftalice \u201eFlat Clinch\u201c i \u201eIntegral\u201c koje se koriste \u0161irom sveta u \u0161tamparijama i kancelarijama.\n\nMAX je poznat i po ure\u0111ajima za obradu \u010dekova namenjenim finansijskom sektoru, kao i sistemima za \u0161tampanje i rezanje etiketa, oznaka i kablova, koji nalaze primenu u industrijskim i obrazovnim okru\u017eenjima.\n\nMAX alati, kancelarijska oprema i ure\u0111aji za specijalizovanu upotrebu nude kompletna re\u0161enja za profesionalce iz razli\u010ditih sektora.\n\nNjihov \u0161irok asortiman \u010dini ih pouzdanim partnerom za sve koji tra\u017ee kvalitet, preciznost i inovaciju.",
          en: "MAX has pioneered many tools on the global market, including the first roofing nailer (1982), battery-powered rebar tying tool (1993), and high-pressure compressors and nailers (1994).\n\nThese tools are widely trusted by professionals for their performance, durability, and ergonomic design.\n\nMAX's industrial tools include powerful yet lightweight devices developed with proprietary features.\n\nThe range covers pneumatic nailers, 20-bar high-pressure compressors, metal and concrete tools, and accessories used in construction.\n\nThe office equipment division includes a variety of staplers, such as the innovative Flat Clinch and Integral models used in copy machines worldwide.\n\nMAX also offers check-processing devices for the financial sector and labeling systems for industrial and educational use, including tube marking tools and cable identification systems.\n\nMAX's diverse portfolio provides complete solutions for professionals across multiple sectors.\n\nIts tools and office equipment stand for reliability, innovation, and performance, making MAX a trusted brand for those who value quality in every task.",
        },
      },
    ],
    catalogs: [
      { name: "MAX katalog", pdfUrl: "https://drive.google.com/file/d/1k3AzwfcE_RlB8xJiO1Tp1nZQwrnEyZje/view?usp=share" },
    ],
    color: "#FFA43B",
    storeUrl: "https://www.prodavnicaalata.rs/proizvodjaci/max/",
  };
