import type { Brand } from "./types";

export const senco: Brand = {
    slug: "senco",
    name: "Senco",
    logoSrc: "/logos/senco-logo.svg",
    description: "SENCO, sinonim za snagu i pouzdanost, nudi izuzetnu kolekciju zakiva\u010da eksera koja zadovoljava visoke standarde u gra\u0111evinskoj industriji.",
    heroDescription: { sr: "Senco alati - Uvoznik za Srbiju", en: "Senco Tools - Importer for Serbia" },
    paragraphs: [
      {
        title: { sr: "Istorijat", en: "History" },
        body: {
          sr: "U 1930-im godinama, osniva\u010d kompanije, Albert Juilfs, radio je iz svog podruma i proizveo Springtramp Eliminator, alat koji je re\u0161avao problem vibracija u automobilima tog vremena.\n\nTaj pionirski duh postavio je temelje za budu\u0107e uspehe brenda SENCO.\n\nVe\u0107 tokom 1940-ih godina, SENCO uvodi revoluciju u industriji alatki, pravi prvi pneumatski alat za spajanje: spajalicu za industrijsku ambala\u017eu i tapaciranje.\n\nOvaj SENCO alat postavlja nove standarde brzine i efikasnosti na proizvodnoj traci i pozicionira brend kao lidera u industriji pri\u010dvr\u0161\u0107iva\u010da i pneumatskih alata.\n\nTokom 1960-ih godina, kompanija otvara prvu fabriku u Sinsinatiju, Ohio.\n\nU toj fabrici proizvodi se nova linija pri\u010dvr\u0161\u0107iva\u010da i pneumatskih alata: ekseri sa papirnom trakom i spiralni ekseri.\n\nZbog rasta potra\u017enje, fabrika se pro\u0161iruje ve\u0107 nakon pet godina.\n\nDevedesetih godina, SENCO lansira ikoni\u010dne modele kao \u0161to su SN325 framerski ekser, SFN40 i SN60 ekserke, kao i SLP20 brad ekser i M2+/M3+ spajalice.\n\nFramePro serija eksera postaje standard za graditelje, stolare i profesionalce koji tra\u017ee pouzdanost i brzinu u radu.\n\nPo\u010detkom 2000-ih, SENCO dodatno modernizuje industriju sa DURASPIN\u00ae be\u017ei\u010dnim auto-hranivim odvija\u010dem, idealnim za brzo i precizno pri\u010dvr\u0161\u0107ivanje.\n\nOva tehnologija integri\u0161e sistem za automatsko hranjenje vijaka, \u0161to \u010dini rad jo\u0161 efikasnijim.\n\nUbrzo sti\u017eu i verzije sa kablom i dodatna oprema.\n\nTokom 2010-ih, SENCO uvodi FUSION\u00ae tehnologiju, inovaciju u be\u017ei\u010dnim 15-Gauge zavr\u0161nim ekserkama koje elimini\u0161u potrebu za gorivnim \u0107elijama.\n\nAlati postaju jo\u0161 prakti\u010dniji, ekonomi\u010dniji i jednostavniji za odr\u017eavanje.\n\nU 2021. godini, nakon akvizicije od strane KYOCERA korporacije (2017), SENCO ula\u017ee u pro\u0161irenje fabrike u Sinsinatiju.\n\nNovi globalni centar konsoliduje sve SENCO resurse, unapre\u0111uju\u0107i inovacije, komunikaciju i razvoj alata za pri\u010dvr\u0161\u0107ivanje.",
          en: "In the 1930s, company founder Albert Juilfs worked from his basement and produced the Springtramp Eliminator, a device that addressed the vibration problem in automobiles of the time.\n\nBy the 1940s, SENCO created the first pneumatic stapler for industrial packaging and upholstery, setting a new standard for ease and speed on the production line.\n\nThis secured the company's future, and today, SENCO focuses on producing high-quality fastening tools.\n\nIn the 1960s, SENCO opened its first factory in Cincinnati, Ohio, where it produced a new line of fastening products\u2014paper-taped nails and coil nails.\n\nThe factory expanded five years later to support the growing production of tools and fasteners.\n\nDuring the 1990s, SENCO launched the SN325 Framing Nail and many other tools that became popular among builders, carpenters, and other professionals, including the SFN40 and SN60 nailers, M2+ and M3+ staplers, SLP20 Brad nailer, and the FramePro nailer series.\n\nIn the 2000s, SENCO revolutionized the collated nail market with its wireless DURASPIN\u00ae screwdriver.\n\nThe technology enabled a fully integrated auto-feed screw system.\n\nLater that year, a corded model and accessories were introduced.\n\nIn the 2010s, SENCO introduced FUSION\u00ae technology with the wireless 15-Gauge finish nailer, which eliminated the need for fuel cells, along with the associated costs and cleaning.\n\nIn 2021, after SENCO was acquired by KYOCERA Corporation in 2017, an investment was announced to expand the factory and bring all SENCO employees in Cincinnati under one roof.\n\nThe new global headquarters will enhance communication and innovation, allowing further progress in the coming years.",
        },
      },
      {
        title: { sr: "Tehnologije i inovacije", en: "Technologies and innovations" },
        body: {
          sr: "SENCO alati prednja\u010de u inovacijama zahvaljuju\u0107i patentiranoj FUSION\u2122 tehnologiji.\n\nOva tehnologija koristi zatvorenu komoru sa komprimovanim vazduhom i baterijski motor koji pru\u017ea performanse poput klasi\u010dnih pneumatskih alata, bez potrebe za gasnim patronama ili odr\u017eavanjem.\n\nDURASPIN\u2122 sistemi sa automatskim hranjenjem vijaka omogu\u0107avaju korisnicima da rade u tesnim prostorima gde konvencionalni alati ne mogu da dopru.\n\nPovratni mehanizam dodatno pobolj\u0161ava preciznost i pove\u0107ava produktivnost do 30%, \u0161to \u010dini DURASPIN savr\u0161enim izborom za profesionalce.\n\nNEVERLUBE\u00ae tehnologija elimini\u0161e potrebu za podmazivanjem SENCO alata.\n\nSuvi podmaziva\u010di i O-prstenovi otporni na isu\u0161ivanje garantuju minimalno odr\u017eavanje, dug vek trajanja i visok u\u010dinak bez dodatnih tro\u0161kova.\n\nSENCOTE, specijalni premaz za SENCO ekseri, smanjuje trenje i pobolj\u0161ava prodor u materijale.\n\nNakon hla\u0111enja, premaz deluje kao vezivni agent, pove\u0107avaju\u0107i snagu dr\u017eanja eksera.\n\nDA stil zavr\u0161nih eksera razvijen od strane SENCO-a idealan je za ugaone ekserke, koje su naro\u010dito korisne za rad u ograni\u010denim prostorima.\n\nAutomatizacija je tako\u0111e klju\u010dni deo SENCO strategije, alati i pri\u010dvr\u0161\u0107iva\u010di lako se integri\u0161u u industrijske sisteme za serijsku proizvodnju.",
          en: "SENCO's revolutionary, patented FUSION\u2122 technology relies on a permanently sealed air chamber and a battery-powered motor that recompresses air repeatedly.\n\nWhile other cordless technologies use slow mechanical flywheels or expensive gas cartridges to drive nails, FUSION\u2122 tools function and perform like pneumatic nailers.\n\nSENCO created the first all-in-one auto-feed screw system with the launch of DURASPIN\u2122.\n\nFeaturing a corner-fit feed system, which allows access to tight spaces other drivers cannot reach, and a new return-feed drive system that improves precision, DURASPIN\u2122 boosts productivity by up to 30%.\n\nSENCO\u2019s patented NEVERLUBE\u00ae technology virtually eliminates routine tool maintenance.\n\nInternal components include a unique graphite composite that serves as a dry lubricant and self-lubricating O-rings that do not dry out.\n\nNEVERLUBE\u00ae tools do not require oiling and never need to be repacked with grease like other oil-free tools.\n\nSENCOTE is a specially formulated nail coating that reduces friction for easier driving.\n\nThe friction melts the coating inside the wood\u2014when it cools, it acts as a bonding agent, increasing holding power.\n\nSENCO also created the popular DA-style finish nail, ideal for nailers with angled magazines that are easier to maneuver in tight spaces.\n\nNailers and DURASPIN systems can be used in manufacturing environments where automation is key.\n\nSENCO tools and technologies can be incorporated into automated framing and screwing tables that build walls and structures with unmatched speed and precision on a massive scale.",
        },
      },
      {
        title: { sr: "Asortiman proizvoda", en: "Product range" },
        body: {
          sr: "SENCO nudi \u0161irok spektar alata za pri\u010dvr\u0161\u0107ivanje, uklju\u010duju\u0107i pneumatske alate, pi\u0161tolje za ekserke, klamerice, spajalice i kompresore.\n\nNjihov asortiman zadovoljava potrebe stolara, gra\u0111evinara i profesionalaca iz svih oblasti.\n\nSENCO pneumatski alati i pri\u010dvr\u0161\u0107iva\u010di omogu\u0107avaju precizno i \u010dvrsto povezivanje materijala, \u010dak i u najzahtevnijim uslovima rada.\n\nBrzo punjenje i ergonomski dizajn omogu\u0107avaju dugotrajan rad bez umora.\n\nNjihovi kompaktni i pouzdani kompresori olak\u0161avaju svakodnevne zadatke, dok su SENCO ekseri i spajalice savr\u0161eno uskla\u0111eni sa alatima, za maksimalnu pouzdanost i vrhunske rezultate.",
          en: "Senco offers a wide range of products, from pneumatic tools to fastening machines, designed to meet the needs of professionals.\n\nTheir nailers and staplers provide precise and strong joints, even in demanding conditions, while models with quick reloading and ergonomic designs allow for long work hours with minimal fatigue.\n\nSenco compressors are compact, powerful, and reliable, enabling efficient work, while their nails and staples perfectly match their tools, providing durable and reliable joints for various projects.",
        },
      },
    ],
    catalogs: [
    ],
    color: "#FF5376",
    storeUrl: "https://www.prodavnicaalata.rs/proizvodjaci/senco/",
  };
