import type { Brand } from "./types";

export const wera: Brand = {
    slug: "wera",
    name: "Wera",
    logoSrc: "/logos/wera-logo.svg",
    description: "Wera je priznata nema\u010dka marka specijalizovana za visokokvalitetne ru\u010dne alate. Projektuje i proizvodi vi\u0161e od 3.000 razli\u010ditih alata.",
    heroDescription: { sr: "Wera alati - Uvoznik za Srbiju", en: "Wera Tools - Importer for Serbia" },
    paragraphs: [
      {
        title: { sr: "Istorijat", en: "History" },
        body: {
          sr: "Godine 1936, preduzetnik Hermann Werner osnovao je Hermann Werner GmbH & Co. KG kao trgovinsku firmu specijalizovanu za prodaju alata. Ova osnova postavila je temelje za ono \u0161to \u0107e kasnije postati globalno prepoznat brend, Wera alati.\n\nDesetak godina kasnije, firma je rekonstruisana pod vo\u0111stvom Heinza Amtenbrinka, zeta porodice Werner. Tada se zapo\u010dinje proizvodnja odvija\u010da, \u0161to je ozna\u010dilo po\u010detak razvoja ru\u010dnih alata pod sopstvenim brendom. Od 1951. godine, kompanija koristi naziv Wera, kombinacijom imena Werner i Amtenbrink, \u010dime je postavljen identitet koji se odr\u017eava i danas.\n\nProizvodnja bitova zapo\u010dela je 1963. godine, a samo pet godina kasnije, u saradnji sa Fraunhofer institutom, razvijena je poznata Kraftform ru\u010dka, jedna od najprepoznatljivijih inovacija u svetu odvija\u010da. Ova ru\u010dka ostala je deo Wera logotipa, simbola kvaliteta i pouzdanosti nema\u010dkih alata.\n\nTokom 1990-ih, Wera Tools uvodi bitove presvu\u010dene dijamantom i \u0161iri se preuzimanjem Drehmax W. Holland i osnivanjem prodajne podru\u017enice u Velikoj Britaniji. Godine 1995, deo proizvodnje se seli u \u010ce\u0161ku Republiku, u grad Byst\u0159ice.\n\nNakon \u0161to se osniva\u010d povukao iz posla, Wera je 2016. godine prodata Bitburger Holdingu. Te iste godine otvoren je moderan logisti\u010dki centar u Wuppertalu, povr\u0161ine 20.000 m\u00b2. Kompanija je tada zapo\u0161ljavala vi\u0161e od 750 ljudi globalno, uklju\u010duju\u0107i vi\u0161e od 400 u \u010ce\u0161koj. Ekspanzija je nastavljena 2018. godine otvaranjem filijale u T\u0159eb\u00ed\u010du.\n\nOd 2019. godine, brend je prisutan i na promotivnim doga\u0111ajima sa svojim balonom u obliku odvija\u010da, isti\u010du\u0107i jedinstven pristup komunikaciji sa korisnicima. Wera alati su postali sinonim za preciznost, pouzdanost i inovacije u alatima.",
          en: "In 1936, entrepreneur Hermann Werner founded Hermann Werner GmbH & Co. KG as a trading company specializing in tools. This laid the foundation for what would later become a globally recognized brand, Wera tools.\n\nThe company was restructured about a decade later under the leadership of Heinz Amtenbrink, Werner\u2019s son-in-law. It was then that the production of screwdrivers began, marking the start of Wera\u2019s own line of hand tools. Since 1951, the company has used the name Wera, a combination of Werner and Amtenbrink, establishing the brand identity that continues to this day.\n\nThe production of bits began in 1963. In 1968, in collaboration with the Fraunhofer Institute, the company developed the iconic Wera Kraftform handle, which remains a part of the Wera logo and reflects the brand\u2019s dedication to ergonomic design in German tools.\n\nDuring the 1990s, Wera Tools introduced diamond-coated bits and expanded by acquiring Drehmax W. Holland and establishing a sales branch in the United Kingdom in 1993. In 1995, manufacturing was relocated to Byst\u0159ice, in the Czech Republic.\n\nFollowing the founder\u2019s retirement, Wera was sold to Bitburger Holding in 2016. That same year, a 20,000 m\u00b2 logistics center was opened in Wuppertal. By then, the company employed over 750 people worldwide, including more than 400 in the Czech Republic. The expansion continued in 2018 with the opening of a new branch in T\u0159eb\u00ed\u010d.\n\nSince 2019, the brand has taken part in promotional events such as Montgolfiade, Kiel Week, and Balloon Cup in the Kitzb\u00fchel Alps with a hot air balloon shaped like a screwdriver, a unique approach to engaging with users. Wera tools have become synonymous with innovation, precision, and professional hand tools.",
        },
      },
      {
        title: { sr: "Tehnologije i inovacije", en: "Technologies and innovations" },
        body: {
          sr: "Wera konstantno unapre\u0111uje dizajn i funkcionalnost svojih profesionalnih alata za ru\u010dnu i elektri\u010dnu upotrebu. Joker ra\u010dni klju\u010devi omogu\u0107avaju lako zatezanje i otpu\u0161tanje navrtki zahvaljuju\u0107i inovativnoj funkciji dr\u017eanja. Impaktor bit sistem je optimizovan za be\u017ei\u010dne udarne odvija\u010de, koriste\u0107i TriTorsion i Diamond tehnologiju za izdr\u017eljivost i efikasnost.\n\nWera nudi i BiTorsion bitove koji podnose velika optere\u0107enja, dok Rapidaptor dr\u017ea\u010di omogu\u0107avaju brzu i sigurnu zamenu bitova \u2013 \u010dak i jednom rukom. Tehnologija Hex-Plus spre\u010dava o\u0161te\u0107enje \u0161rafova sa \u0161esterougaonim glavama, dok Zyklop ra\u010dne kombinuju vi\u0161e funkcija i kompatibilne su sa razli\u010ditim \u010daurama.\n\nMe\u0111u najinovativnijim re\u0161enjima isti\u010du se Koloss ra\u010dna, koja slu\u017ei i kao \u010deki\u0107, kao i Chiseldriver odvija\u010d koji podnosi udarce bez gubitka preciznosti. Kraftform Kompakt setovi dolaze sa futrolama i selekcijom bitova, idealni za prenos. Posebnu pa\u017enju zaslu\u017euju Wera Stainless alati \u2013 izra\u0111eni od ner\u0111aju\u0107eg \u010delika, savr\u0161eni za za\u0161titu od korozije.",
          en: "Wera continually enhances the design and functionality of its professional tools for both manual and power tool applications. Joker combination ratchet wrenches feature a holding function that allows stable tightening and loosening of nuts. The Impaktor bit system is designed for cordless impact drivers and incorporates TriTorsion and Diamond technology for increased durability and performance.\n\nThe BiTorsion bits are built to withstand higher loads, while Rapidaptor bit holders allow for quick and secure one-handed bit changes. Hex-Plus technology prevents rounding of screws with hex heads, extending their service life. Zyklop ratchets combine multiple functions and are compatible with sockets of various sizes.\n\nAmong Wera\u2019s standout tools are the Koloss ratchet, which doubles as a hammer without damaging the tool, and the Chiseldriver, a screwdriver that can be struck with a hammer yet still offers precise screwdriving capabilities. Kraftform Kompakt sets come with holders and a selection of bits packed in hard or soft cases for easy transport. Wera Stainless tools, made from stainless steel, help prevent corrosion caused by contact with dissimilar metals.",
        },
      },
      {
        title: { sr: "Asortiman proizvoda", en: "Product range" },
        body: {
          sr: "Wera projektuje i proizvodi vi\u0161e od 3.000 razli\u010ditih alata, uklju\u010duju\u0107i imbus klju\u010deve, ra\u010dne, \u010daure, odvija\u010de, bitove i kompletne setove alata. Sedi\u0161te kompanije je u Nema\u010dkoj, dok se proizvodnja odvija i u fabrici u \u010ce\u0161koj Republici.\n\nKroz svoju prodajnu platformu Wera Tool Rebels GmbH, brend nudi direktnu kupovinu alata za zavrtanje \u0161irom sveta. Kompanija je poznata po integraciji vi\u0161e funkcionalnosti u jedan alat, \u0161to korisnicima \u0161tedi vreme i pove\u0107ava efikasnost. Na primer, ra\u010dunasti klju\u010devi sa dodatnim funkcijama omogu\u0107avaju rad u te\u0161kim uslovima bez dodatnih alata.\n\nWera je prepoznatljiva po svojim odvija\u010dima sa Kraftform ru\u010dkom, dizajniranom za optimalno prianjanje i ergonomiju. Prepoznatljive \u201ckrune\u201d na ru\u010dki deo su vizuelnog identiteta brenda, simbolizuju\u0107i preciznost i inovaciju.",
          en: "Wera designs and manufactures over 3,000 tools including Allen keys, ratchets, sockets, screwdrivers, bits, tool sets, and compact tools. The company\u2019s headquarters is in Germany, with production facilities in the Czech Republic.\n\nThrough its subsidiary Wera Tool Rebels GmbH, the brand operates an online store for direct customer access. Wera specializes in screwdriving tools and is known for integrating multiple functions into one tool, enhancing efficiency and reducing the need for multiple instruments. For instance, their wrenches and ratchets feature advanced functionalities tailored for demanding work environments.\n\nThe brand is best known for its screwdrivers with Kraftform handles, designed to match the contours of the hand, featuring soft and hard gripping zones. The signature \u201ccrowns\u201d on the handles are part of the Wera logo, symbolizing innovation and ergonomic excellence in German tool manufacturing.",
        },
      },
      {
        title: { sr: "Nagrade", en: "Awards" },
        body: {
          sr: "Kao dokaz kvaliteta i inovacija, Wera Tools je dobitnik brojnih nagrada u oblasti dizajna i upravljanja brendom. Me\u0111u najva\u017enijima su iF Product Design Award (1997, 2009, 2012, 2013, 2015. uklju\u010duju\u0107i Zlatnu nagradu), Red Dot Design Award (\u201eBest of the Best\u201c u 2014. i nagrada 2015), i German Design Award 2015. godine.\n\nU oblasti komunikacije, Wera je tako\u0111e nagra\u0111ena Red Dot Design Award 2014. godine, a u upravljanju brendom, German Brand Award tri godine zaredom (2015\u20132017). Kompanija je 2007. godine progla\u0161ena za Top Innovator-a, dok je 2016. i 2021. godine osvojila prvo mesto u industrijskoj kategoriji Partner des Fachhandels.",
          en: "Over the years, Wera Tools has received numerous awards for product design, brand management, and innovation. In product design, Wera has won the iF Product Design Award in 1997, 2009, 2012, 2013, and 2015, including the prestigious Gold Award. The company also earned the Red Dot Design Award in 2014 for \u201cBest of the Best,\u201d and again in 2015.\n\nIn communication design, Wera received the Red Dot Design Award in 2014 and the German Design Award in 2015. For excellence in brand management, the company was honored with the German Brand Award from 2015 to 2017. In 2007, Wera was named a Top Innovator. In the industrial tools sector, Wera claimed first place in the \u201cPartner des Fachhandels\u201d award in both 2016 and 2021.",
        },
      },
    ],
    catalogs: [
      { name: "Wera katalog", pdfUrl: "https://drive.google.com/file/d/140HnM3JRm2k_F4iF_j46tbchAST-S45O/view?usp=share" },
    ],
    color: "#05B920",
    storeUrl: "https://www.prodavnicaalata.rs/proizvodjaci/wera/",
  };
