import type { Dealer } from "@brand/shared/types/dealers";

export const DEALERS: Dealer[] = [
  // === Online distributeri ===
  {
    id: "tim-komerc",
    name: "TIM KOMERC D.O.O.",
    address: "Paunova 8",
    city: "Beograd",
    email: "tim.1@mts.rs",
    website: "https://timkomerc.rs/",
    category: "online",
    coordinates: { lat: 44.8176, lng: 20.4633 },
  },
  {
    id: "zim-commerce",
    name: "ZIM COMMERCE D.O.O.",
    city: "Zrenjanin",
    phone: "024/577-566",
    email: "zimcommercedoo@gmail.com",
    website: "https://zimcommerce.com/sr",
    category: "online",
    coordinates: { lat: 45.3816, lng: 20.3903 },
  },
  {
    id: "kliklak-racunari",
    name: "KLIKLAK RAČUNARI",
    address: "Matejevački put 36",
    city: "Niš",
    email: "info@kliklak.rs",
    website: "https://www.kliklak.rs/",
    category: "online",
    coordinates: { lat: 43.3209, lng: 21.8958 },
  },
  {
    id: "od-igle-do-lokomotive",
    name: "OD IGLE DO LOKOMOTIVE D.O.O.",
    address: "Radoja Dakića",
    city: "Niš",
    phone: "018/575-773",
    email: "office@odigledolokomotive.rs",
    category: "online",
    coordinates: { lat: 43.3167, lng: 21.8954 },
  },
  {
    id: "sualati024",
    name: "SUALATI024 D.O.O.",
    address: "Segedinski put 86",
    city: "Subotica",
    phone: "024/525-091",
    email: "sualati@gmail.com",
    website: "https://www.sualati.com/",
    category: "online",
    coordinates: { lat: 46.0964, lng: 19.6706 },
  },
  {
    id: "iskra-servis",
    name: "ISKRA SERVIS D.O.O.",
    address: "Mije Kovačevića 10",
    city: "Beograd",
    phone: "011/3290-295",
    email: "kontakt@iskraservis.pro",
    website: "https://www.iskraservis.pro/",
    category: "online",
    coordinates: { lat: 44.7942, lng: 20.4747 },
  },
  {
    id: "maxidom",
    name: "MAXIDOM D.O.O.",
    address: "Pančevački put 81",
    city: "Beograd",
    phone: "011/4240-400",
    email: "info@maxidom.rs",
    website: "https://maxidom.rs/",
    category: "online",
    coordinates: { lat: 44.8198, lng: 20.4897 },
  },
  {
    id: "mixal",
    name: "MIXAL D.O.O.",
    address: "Gandijeva 3, lokal 10",
    city: "Novi Beograd",
    phone: "011/2289-103",
    email: "info@mixalshop.rs",
    website: "https://najpovoljnijialati.rs/",
    category: "online",
    coordinates: { lat: 44.8148, lng: 20.4103 },
  },
  {
    id: "sistem-cd",
    name: "S.Z.T.K.R. SISTEM CD",
    address: "Dragoslava Srejovića 32",
    city: "Beograd",
    phone: "062/241-661",
    email: "Office@sistemcd.rs",
    website: "https://www.queencolor.rs/",
    category: "online",
    coordinates: { lat: 44.8042, lng: 20.4728 },
  },
  {
    id: "stridon-group-online",
    name: "Stridon Group D.O.O.",
    address: "Vojislava Ilića 141g",
    city: "Beograd",
    phone: "011/4520-171",
    email: "office@stridon.rs",
    website: "https://www.prodavnicaalata.rs/",
    category: "online",
    coordinates: { lat: 44.7724, lng: 20.4989 },
  },

  // === Ovlašćeni servisni centri i dileri ===
  {
    id: "metalka-alati",
    name: "METALKA-ALATI D.O.O.",
    city: "Pančevo",
    category: "dealer",
    coordinates: { lat: 44.8708, lng: 20.6403 },
  },
  {
    id: "alati-dms",
    name: "ALATI DMS D.O.O.",
    city: "Ralja",
    category: "dealer",
    coordinates: { lat: 44.5122, lng: 20.6592 },
  },
  {
    id: "dabs-alati",
    name: "D.A.B.S. ALATI D.O.O.",
    city: "Novi Beograd",
    category: "dealer",
    coordinates: { lat: 44.8044, lng: 20.3995 },
  },
  {
    id: "alfa-022",
    name: "ALFA 022 D.O.O.",
    city: "Ruma",
    category: "dealer",
    coordinates: { lat: 45.0079, lng: 19.8228 },
  },
  {
    id: "stolarski-centar",
    name: "STOLARSKI CENTAR TR",
    city: "Sremska Mitrovica",
    category: "dealer",
    coordinates: { lat: 44.9764, lng: 19.6122 },
  },
  {
    id: "mk-decor-24",
    name: "MK DECOR 24 KRISTINA PETROVIĆ",
    city: "Stepojevac",
    category: "dealer",
    coordinates: { lat: 44.532, lng: 20.2714 },
  },
  {
    id: "silmax",
    name: "SILMAX D.O.O.",
    city: "Kraljevo",
    category: "dealer",
    coordinates: { lat: 43.7232, lng: 20.6869 },
  },
  {
    id: "mimi-z",
    name: "MIMI Z STR ŽELJKO TOMIĆ PR",
    city: "Šabac",
    category: "dealer",
    coordinates: { lat: 44.7477, lng: 19.6897 },
  },
  {
    id: "tojo-pozega",
    name: "TOJO D.O.O. POŽEGA",
    city: "Požega",
    category: "dealer",
    coordinates: { lat: 43.8464, lng: 20.0378 },
  },
  {
    id: "tojo-uzice",
    name: "TOJO D.O.O. UŽICE",
    city: "Užice",
    category: "dealer",
    coordinates: { lat: 43.8575, lng: 19.8486 },
  },
  {
    id: "erdevicki-elektrohouse",
    name: "ERDEVIČKI ELEKTROHOUSE DOO",
    city: "Beograd",
    category: "dealer",
    coordinates: { lat: 44.7461, lng: 20.5456 },
  },
  {
    id: "srafko-com",
    name: "ŠRAFKO COM D.O.O.",
    city: "Smederevo",
    category: "dealer",
    coordinates: { lat: 44.6626, lng: 20.9272 },
  },
  {
    id: "vsg-sistem",
    name: "VSG SISTEM DOO",
    city: "Mali Mokri Lug",
    category: "dealer",
    coordinates: { lat: 44.7789, lng: 20.528 },
  },
  {
    id: "senjak-komerc",
    name: "SENJAK KOMERC D.O.O.",
    city: "Beograd",
    category: "dealer",
    coordinates: { lat: 44.82, lng: 20.485 },
  },
  {
    id: "mikra-coop",
    name: "MIKRA COOP DOO",
    city: "Bačka Topola",
    category: "dealer",
    coordinates: { lat: 45.8148, lng: 19.6321 },
  },
  {
    id: "str-balaton",
    name: "STR BALATON",
    city: "Beograd",
    category: "dealer",
    coordinates: { lat: 44.825, lng: 20.51 },
  },
  {
    id: "esad-krkusic",
    name: "ESAD KRKUSIĆ PR",
    city: "Novi Pazar",
    category: "dealer",
    coordinates: { lat: 43.1367, lng: 20.5122 },
  },
  {
    id: "tehnoalat",
    name: "TEHNOALAT D.O.O.",
    city: "Valjevo",
    category: "dealer",
    coordinates: { lat: 44.2728, lng: 19.8914 },
  },
  {
    id: "tehnonis",
    name: "TEHNONIŠ D.O.O.",
    city: "Niš",
    category: "dealer",
    coordinates: { lat: 43.3185, lng: 21.8963 },
  },

  // === Ovlašćeni servisi ===
  {
    id: "hammercom",
    name: "Hammercom D.O.O.",
    address: "Valjevska 3",
    city: "Beograd",
    phone: "011/6543-683",
    email: "office@hammercom.co.rs",
    website: "http://www.hammercom.co.rs/",
    category: "service",
    coordinates: { lat: 44.7871, lng: 20.4568 },
  },
  {
    id: "dm-elektro",
    name: "Elektroservis DM Elektro PR",
    address: "Jaše Prodanovića 18",
    city: "Čačak",
    phone: "063/883-31060",
    email: "dmelektro032@gmail.com",
    category: "service",
    coordinates: { lat: 43.8914, lng: 20.3497 },
  },
  {
    id: "servis-mitic",
    name: "SZR Servis Mitić",
    address: "Surčinska 103d",
    city: "Novi Beograd",
    phone: "011/2260-135",
    website: "http://www.servisalata-mitic.com",
    category: "service",
    coordinates: { lat: 44.7983, lng: 20.3876 },
  },

  // === Servis van garantnog roka ===
  {
    id: "stridon-group-oow",
    name: "Stridon Group D.O.O.",
    address: "Vojislava Ilića 141g",
    city: "Beograd",
    phone: "011/4520-171",
    email: "office@stridon.rs",
    website: "https://www.prodavnicaalata.rs/",
    category: "outOfWarranty",
    coordinates: { lat: 44.7724, lng: 20.4989 },
  },
];

export const UNIQUE_DEALER_NAMES = [
  ...new Set(DEALERS.map((d) => d.name)),
].sort((a, b) => a.localeCompare(b, "sr"));
